export type Decision = "APPROVE" | "REVIEW" | "DECLINE";

/** A validated transaction ready to be evaluated. `id` is generated by the caller. */
export interface Transaction {
  id: string;
  accountId: string;
  amount: number;
  currency: string;
  /** ISO 3166-1 alpha-2, uppercase. */
  countryCode: string;
  /** Epoch milliseconds. */
  timestamp: number;
  merchant?: string;
  channel?: string;
}

/** JSON-safe values only, so hits survive workflow step and RPC serialization. */
export type Evidence = Record<string, string | number | boolean | string[]>;

export interface RuleHit {
  rule: string;
  weight: number;
  message: string;
  evidence: Evidence;
}

export interface Evaluation {
  score: number;
  hits: RuleHit[];
  decision: Decision;
}

export interface TriageResult extends Evaluation {
  transaction: Transaction;
  explanation: string;
  caseId: string | null;
}

export interface CaseRecord {
  id: string;
  txnId: string;
  ts: number;
  decision: Decision;
  score: number;
  hits: RuleHit[];
  explanation: string;
  status: string;
}

/** A case joined with the transaction that opened it, for explanations. */
export interface CaseDetail {
  caseId: string;
  status: string;
  decision: Decision;
  score: number;
  hits: RuleHit[];
  explanation: string;
  transaction: {
    id: string;
    ts: number;
    amount: number;
    currency: string;
    countryCode: string;
    merchant: string | null;
    channel: string | null;
  };
}

export interface StoredTransaction {
  id: string;
  ts: number;
  amount: number;
  currency: string;
  countryCode: string;
  merchant: string | null;
  channel: string | null;
  decision: Decision;
  score: number;
  hits: RuleHit[];
}
